/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: vinrax (https://sketchfab.com/vinrax)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/male-character-ps1-style-78640adbd76b48129e9316259695c742
Title: Male Character PS1-Style
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

import scene from '../assets/3d/male_character_ps1-style.glb'

export function Character(props) {
    const { nodes, materials } = useGLTF(scene)
    return (
        <group {...props} dispose={null}>
            <group rotation={[-Math.PI / 2, 0, 0]}>
                <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
                    <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                        <primitive object={nodes._rootJoint} />
                        <skinnedMesh
                            geometry={nodes.Object_7.geometry}
                            material={materials.hero}
                            skeleton={nodes.Object_7.skeleton}
                        />
                    </group>
                </group>
            </group>
        </group>
    )
}

useGLTF.preload(scene)