/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: NO DONT EAT ME CASEOH (Ferris wheel) (https://sketchfab.com/NO.DONT.EAT.ME.CASEOH)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/merio-rig-08e53e91436846bf8c045ccd6de44010
Title: Merio Rig
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import scene from '../assets/3d/bob.glb'

export function Mario({ animation, ...props }) {
    const group = useRef()
    const { nodes, materials, animations } = useGLTF(scene)
    const { actions } = useAnimations(animations, group)


    useEffect(() => {
        actions[animation]?.reset().fadeIn(0.24).play();
        return () => actions[animation]?.fadeOut(0.24);
    }, [animation])
    return (
        <group ref={group} {...props} dispose={null}>
            <group name="Scene">
                <group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={50}>
                    <skinnedMesh
                        name="Stickman"
                        geometry={nodes.Stickman.geometry}
                        material={materials['Material.001']}
                        skeleton={nodes.Stickman.skeleton}
                    />
                    <primitive object={nodes.mixamorigHips} />
                </group>
            </group>
        </group>
    )
}

useGLTF.preload(scene)
