/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: NO DONT EAT ME CASEOH (Ferris wheel) (https://sketchfab.com/NO.DONT.EAT.ME.CASEOH)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/merio-rig-08e53e91436846bf8c045ccd6de44010
Title: Merio Rig
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import scene from '../assets/3d/merio_rig.glb'

export function Mario({ animation, ...props }) {
    const group = useRef()
    const { nodes, materials, animations } = useGLTF(scene)
    const { actions } = useAnimations(animations, group)


    useEffect(() => {
        actions[animation]?.reset().fadeIn(0.24).play();
        return () => actions[animation]?.fadeOut(0.24);
    }, [animation])
    return (
        <group ref={group} {...props} dispose={null}>
            <group name="Sketchfab_Scene">
                <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
                    <group
                        name="c2895b2b8bb446c0a2de3611d29fbdcffbx"
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={0.01}>
                        <group name="Object_2">
                            <group name="RootNode">
                                <group name="merio_belt" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                                <group name="merio_body" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                                <group name="merio_body2" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                                <group name="merio_eyes" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                                <group name="merio_hair" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                                <group name="merio_hands" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                                <group name="merio_hat" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                                <group name="merio_misc" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                                <group name="merio_moustache" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                                <group name="merio_neckhead" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                                <group name="merio_shoes" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                                <group name="merio_belt_skeleton" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                                    <group name="Object_16">
                                        <primitive object={nodes._rootJoint} />
                                        <skinnedMesh
                                            name="Object_19"
                                            geometry={nodes.Object_19.geometry}
                                            material={materials.brown}
                                            skeleton={nodes.Object_19.skeleton}
                                        />
                                        <skinnedMesh
                                            name="Object_20"
                                            geometry={nodes.Object_20.geometry}
                                            material={materials.yellow}
                                            skeleton={nodes.Object_20.skeleton}
                                        />
                                        <skinnedMesh
                                            name="Object_22"
                                            geometry={nodes.Object_22.geometry}
                                            material={materials.material}
                                            skeleton={nodes.Object_22.skeleton}
                                        />
                                        <skinnedMesh
                                            name="Object_23"
                                            geometry={nodes.Object_23.geometry}
                                            material={materials.blue}
                                            skeleton={nodes.Object_23.skeleton}
                                        />
                                        <skinnedMesh
                                            name="Object_25"
                                            geometry={nodes.Object_25.geometry}
                                            material={materials.blue}
                                            skeleton={nodes.Object_25.skeleton}
                                        />
                                        <skinnedMesh
                                            name="Object_27"
                                            geometry={nodes.Object_27.geometry}
                                            material={materials.eyeball}
                                            skeleton={nodes.Object_27.skeleton}
                                        />
                                        <skinnedMesh
                                            name="Object_29"
                                            geometry={nodes.Object_29.geometry}
                                            material={materials.brown2}
                                            skeleton={nodes.Object_29.skeleton}
                                        />
                                        <skinnedMesh
                                            name="Object_31"
                                            geometry={nodes.Object_31.geometry}
                                            material={materials.skin}
                                            skeleton={nodes.Object_31.skeleton}
                                        />
                                        <skinnedMesh
                                            name="Object_33"
                                            geometry={nodes.Object_33.geometry}
                                            material={materials.material_7}
                                            skeleton={nodes.Object_33.skeleton}
                                        />
                                        <skinnedMesh
                                            name="Object_35"
                                            geometry={nodes.Object_35.geometry}
                                            material={materials.yellow}
                                            skeleton={nodes.Object_35.skeleton}
                                        />
                                        <skinnedMesh
                                            name="Object_37"
                                            geometry={nodes.Object_37.geometry}
                                            material={materials.brown2}
                                            skeleton={nodes.Object_37.skeleton}
                                        />
                                        <skinnedMesh
                                            name="Object_39"
                                            geometry={nodes.Object_39.geometry}
                                            material={materials.skin}
                                            skeleton={nodes.Object_39.skeleton}
                                        />
                                        <skinnedMesh
                                            name="Object_41"
                                            geometry={nodes.Object_41.geometry}
                                            material={materials.grey}
                                            skeleton={nodes.Object_41.skeleton}
                                        />
                                        <group name="Object_18" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                                        <group name="Object_21" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                                        <group name="Object_24" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                                        <group name="Object_26" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                                        <group name="Object_28" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                                        <group name="Object_30" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                                        <group name="Object_32" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                                        <group name="Object_34" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                                        <group name="Object_36" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                                        <group name="Object_38" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                                        <group name="Object_40" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                                    </group>
                                </group>
                            </group>
                        </group>
                    </group>
                </group>
            </group>
        </group>
    )
}

useGLTF.preload(scene)
